apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80 # The port exposed by the service
    targetPort: 80 # The port to forward traffic to in the pods
  type: LoadBalancer # Use LoadBalancer to expose the service to the internet
